
storage_driver="redis"
listen="127.0.0.1:55555"
daemon=true

[storage.redis]

host="127.0.0.1"
port=6379
password=""
dbname="0"

[storage.mysql]

username="root"
password="root"
dbname="tuna"
host="127.0.0.1"
port=3306

[storage.sqlite]

dbname="/var/run/tuna.db"
